sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t linuxkidvoid/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true linuxkid/docker-react npm run test