sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jiangao1/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jiangao1/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react2"
  env: "Dockerreact2-env"
  bucket_name: "elasticbeanstalk-us-east-1-489558117145"
  bucket_path: "docker-react2"
  on:
    branch: master
  access_key_id: $aws_access_key
  secret_access_key: "$aws_secret_key"